source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.3"
# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"

# MongoDB
gem 'mongoid', '~> 8.0'

# NEO4J
gem 'activegraph', '~> 11.5.0.beta2'
gem 'neo4j-ruby-driver', '>= 4.4', '< 5'

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem 'bcrypt', '~> 3.1.7'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false
gem 'kaminari-mongoid'

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem 'rack-cors'

# To enable dotenv files
gem 'dotenv-rails', groups: [:development, :test]

# Using sqlite3 for testing
gem 'sqlite3', group: :test

# Pagination
gem 'kaminari'

# Jwt for auth
gem 'jwt'

# Google OAuth SSO
gem 'google-id-token'

# OpenAI
gem 'openai'

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# FastImage to ensure real image files are uploaded
gem 'fastimage'

# Using Redis as adapter for action cable
gem 'redis'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false
  gem 'bundler-audit', require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false

  # Test coverage tracking tool
  gem 'simplecov', require: false
  gem 'simplecov_json_formatter', require: false

  # Rspec for TDD
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'webmock'
  gem 'shoulda-matchers', '~> 5.0'
end
